### ISSUE TITLE
junk in examples/

### ISSUE THREAD

**Issue by rofl0r** [orangeduck/tgc#14]
while certainly of high historic value, the 46 MB .wav file with a JFK speech seems out-of-place, just like the source code of bzip2 and oggencoder.

**Comment by orangeduck** [comment]
These are actually used for testing: I.E. they are used when you run `make check`. I though these were good decent sized C projects to evaluate the performance and stability of the gc when using it instead of normal memory management. Of course you do not need to include this examples directory in your own copy of the project.

**Comment by rofl0r** [comment]
alright... tgc now features in the not-yet-100% ready tinyrb branch here https://github.com/rofl0r/tinyrb/tree/TGC (still fighting with some bugs). nice product!

**Comment by orangeduck** [comment]
Very cool, thanks!
